---
- name: restart compose
  community.docker.docker_compose_v2:
    project_src: "{{ haflux_install_dir }}"
    files:
      - compose.yml
    state: present
    pull: missing
    build: "{{ 'always' if haflux_image_source == 'build' else 'never' }}"
