import { Injectable } from '@nestjs/common';
import type { Prisma } from '@prisma/client';
import { PrismaService } from '../../prisma/prisma.service';
import type { RenderedTree } from '../types';

/**
 * Разворачивает кластер из БД в дерево файлов конфига HAProxy.
 *
 * Раскладка (совместима с haproxy:3.x-alpine):
 *   haproxy.cfg                  — global + defaults + (опц. peers/userlist)
 *   conf.d/10-resolvers.cfg
 *   conf.d/20-userlist.cfg
 *   conf.d/30-frontends.cfg
 *   conf.d/40-backends.cfg
 *   conf.d/50-listen.cfg
 *   conf.d/60-peers.cfg
 *   conf.d/70-http-errors.cfg
 *   conf.d/80-rings.cfg
 *   maps/<name>.map
 *   acl/<name>.lst
 *   errors/<name>.http
 *   lua/<name>.lua
 *   spoe/<name>.cfg
 *
 * Renderer должен быть детерминированным — при одинаковом стейте даёт байт-в-байт
 * одинаковый вывод (это важно для diff в git-истории конфига).
 */
@Injectable()
export class CfgRenderer {
  constructor(private readonly prisma: PrismaService) {}

  async render(clusterId: string): Promise<RenderedTree> {
    const cluster = await this.prisma.cluster.findUnique({
      where: { id: clusterId },
      include: {
        global: true,
        defaults: { orderBy: { name: 'asc' } },
        frontends: {
          include: { binds: { include: { cert: true } }, acls: true, httpRules: true, tcpRules: true },
          orderBy: { name: 'asc' },
        },
        backends: {
          include: { servers: true, acls: true, httpRules: true, tcpRules: true },
          orderBy: { name: 'asc' },
        },
        listens: {
          include: { binds: { include: { cert: true } }, servers: true },
          orderBy: { name: 'asc' },
        },
        peers: { orderBy: { name: 'asc' } },
        resolvers: { orderBy: { name: 'asc' } },
        userlists: { orderBy: { name: 'asc' } },
        httpErrors: { orderBy: { name: 'asc' } },
        rings: { orderBy: { name: 'asc' } },
        caches: { orderBy: { name: 'asc' } },
        maps: { orderBy: { name: 'asc' } },
        aclLists: { orderBy: { name: 'asc' } },
        errorFiles: { orderBy: { name: 'asc' } },
        luaScripts: { orderBy: { name: 'asc' } },
        spoeAgents: { orderBy: { name: 'asc' } },
      },
    });

    if (!cluster) throw new Error(`Cluster ${clusterId} not found`);

    const files = new Map<string, string | Buffer>();

    files.set('haproxy.cfg', this.renderMain(cluster));

    if (cluster.resolvers.length) files.set('conf.d/10-resolvers.cfg', this.renderResolvers(cluster.resolvers));
    if (cluster.userlists.length) files.set('conf.d/20-userlists.cfg', this.renderUserlists(cluster.userlists));
    if (cluster.frontends.length) files.set('conf.d/30-frontends.cfg', this.renderFrontends(cluster.frontends));
    if (cluster.backends.length) files.set('conf.d/40-backends.cfg', this.renderBackends(cluster.backends));
    if (cluster.listens.length) files.set('conf.d/50-listen.cfg', this.renderListens(cluster.listens));
    if (cluster.peers.length) files.set('conf.d/60-peers.cfg', this.renderPeers(cluster.peers));
    if (cluster.httpErrors.length) files.set('conf.d/70-http-errors.cfg', this.renderHttpErrors(cluster.httpErrors));
    if (cluster.rings.length) files.set('conf.d/80-rings.cfg', this.renderRings(cluster.rings));
    if (cluster.caches.length) files.set('conf.d/85-caches.cfg', this.renderCaches(cluster.caches));

    for (const map of cluster.maps) {
      files.set(`maps/${map.name}.map`, this.renderMapEntries(map.entries as Array<{ key: string; value: string }>));
    }
    for (const acl of cluster.aclLists) {
      files.set(`acl/${acl.name}.lst`, this.renderAclList(acl.entries as string[]));
    }
    for (const err of cluster.errorFiles) {
      files.set(`errors/${err.name}.http`, err.content);
    }
    for (const lua of cluster.luaScripts) {
      files.set(`lua/${lua.name}.lua`, lua.source);
    }
    for (const spoe of cluster.spoeAgents) {
      files.set(`spoe/${spoe.name}.cfg`, this.renderSpoeAgent(spoe));
    }

    return { files };
  }

  // ────────────────────────────────────────────────────────────────────────

  private header(): string {
    return [
      '# Generated by HAFlux. DO NOT EDIT MANUALLY.',
      `# Render time: ${new Date().toISOString()}`,
      '',
    ].join('\n');
  }

  private renderMain(cluster: ClusterWithIncludes): string {
    const out: string[] = [this.header()];
    out.push(this.renderGlobal(cluster.global));
    for (const def of cluster.defaults) {
      out.push(this.renderDefaults(def));
    }
    return out.join('\n');
  }

  private renderGlobal(g: NonNullable<ClusterWithIncludes['global']> | null): string {
    const lines: string[] = ['global'];
    if (!g) {
      lines.push('  maxconn 40000');
      lines.push('  daemon');
      lines.push('  log stdout local0 info');
      lines.push('');
      return lines.join('\n');
    }
    lines.push(`  maxconn ${g.maxconn}`);
    if (g.nbthread) lines.push(`  nbthread ${g.nbthread}`);
    if (g.cpuMap) lines.push(`  cpu-map ${g.cpuMap}`);
    if (g.daemon) lines.push('  daemon');
    if (g.pidfile) lines.push(`  pidfile ${g.pidfile}`);
    if (g.masterCliSocket) {
      lines.push(`  stats socket ${g.masterCliSocket} mode 0660 level admin expose-fd listeners`);
    }
    if (g.sslDefaultBindCiphers) lines.push(`  ssl-default-bind-ciphers ${g.sslDefaultBindCiphers}`);
    if (g.sslDefaultBindCiphersuites) {
      lines.push(`  ssl-default-bind-ciphersuites ${g.sslDefaultBindCiphersuites}`);
    }
    if (g.sslDefaultBindOptions) lines.push(`  ssl-default-bind-options ${g.sslDefaultBindOptions}`);
    if (g.sslDhParamFile) lines.push(`  ssl-dh-param-file ${g.sslDhParamFile}`);

    const tune = (g.tune as Record<string, string | number | boolean> | null) ?? {};
    for (const [k, v] of Object.entries(tune)) {
      lines.push(`  tune.${k} ${v}`);
    }

    const logTargets =
      (g.logTargets as Array<{ address: string; format?: string; facility?: string; level?: string }> | null) ?? [];
    for (const lt of logTargets) {
      const parts = [`  log ${lt.address}`];
      if (lt.format) parts.push(`format ${lt.format}`);
      if (lt.facility) parts.push(lt.facility);
      if (lt.level) parts.push(lt.level);
      lines.push(parts.join(' '));
    }
    if (logTargets.length === 0) lines.push('  log stdout local0 info');

    if (g.rawExtra) lines.push(indent(g.rawExtra, 2));
    lines.push('');
    return lines.join('\n');
  }

  private renderDefaults(def: ClusterWithIncludes['defaults'][number]): string {
    const lines: string[] = [];
    const header = def.name && def.name !== 'default' ? `defaults ${def.name}` : 'defaults';
    lines.push(header);
    lines.push(`  mode ${def.mode}`);

    const options = (def.options as Record<string, boolean | string> | null) ?? {};
    for (const [k, v] of Object.entries(options)) {
      if (v === true) lines.push(`  option ${k}`);
      else if (v === false) lines.push(`  no option ${k}`);
      else lines.push(`  option ${k} ${v}`);
    }

    const timeouts = (def.timeouts as Record<string, string> | null) ?? { connect: '5s', client: '30s', server: '30s' };
    for (const [k, v] of Object.entries(timeouts)) lines.push(`  timeout ${k} ${v}`);

    const errorfile = (def.errorfile as Record<string, string> | null) ?? {};
    for (const [code, path] of Object.entries(errorfile)) {
      lines.push(`  errorfile ${code} ${path}`);
    }

    if (def.logFormat) lines.push(`  log-format ${quoteIfNeeded(def.logFormat)}`);
    if (def.rawExtra) lines.push(indent(def.rawExtra, 2));
    lines.push('');
    return lines.join('\n');
  }

  private renderFrontends(frontends: ClusterWithIncludes['frontends']): string {
    const out = [this.header()];
    for (const f of frontends) {
      const lines: string[] = [`frontend ${f.name}`, `  mode ${f.mode}`];
      for (const b of f.binds) {
        lines.push(`  ${this.renderBind(b)}`);
      }
      for (const a of f.acls) {
        lines.push(`  acl ${a.name} ${a.expression}`);
      }
      for (const r of f.httpRules.sort((x, y) => x.ordinal - y.ordinal)) {
        lines.push(`  ${this.renderHttpRule(r)}`);
      }
      for (const r of f.tcpRules.sort((x, y) => x.ordinal - y.ordinal)) {
        lines.push(`  ${this.renderTcpRule(r)}`);
      }
      const options = (f.options as Record<string, boolean | string> | null) ?? {};
      for (const [k, v] of Object.entries(options)) {
        if (v === true) lines.push(`  option ${k}`);
        else if (v === false) lines.push(`  no option ${k}`);
        else lines.push(`  option ${k} ${v}`);
      }
      const timeouts = (f.timeouts as Record<string, string> | null) ?? {};
      for (const [k, v] of Object.entries(timeouts)) lines.push(`  timeout ${k} ${v}`);
      if (f.logFormat) lines.push(`  log-format ${quoteIfNeeded(f.logFormat)}`);
      if (f.defaultBackend) lines.push(`  default_backend ${f.defaultBackend}`);
      if (f.rawExtra) lines.push(indent(f.rawExtra, 2));
      lines.push('');
      out.push(lines.join('\n'));
    }
    return out.join('\n');
  }

  private renderBackends(backends: ClusterWithIncludes['backends']): string {
    const out = [this.header()];
    for (const b of backends) {
      const lines: string[] = [`backend ${b.name}`, `  mode ${b.mode}`, `  balance ${b.balance}`];
      const options = (b.options as Record<string, boolean | string> | null) ?? {};
      for (const [k, v] of Object.entries(options)) {
        if (v === true) lines.push(`  option ${k}`);
        else if (v === false) lines.push(`  no option ${k}`);
        else lines.push(`  option ${k} ${v}`);
      }
      const timeouts = (b.timeouts as Record<string, string> | null) ?? {};
      for (const [k, v] of Object.entries(timeouts)) lines.push(`  timeout ${k} ${v}`);

      const httpCheck = b.httpCheck as { uri?: string; method?: string; expectStatus?: string } | null;
      if (b.mode === 'http' && httpCheck) {
        lines.push(`  option httpchk ${httpCheck.method ?? 'GET'} ${httpCheck.uri ?? '/'}`);
        if (httpCheck.expectStatus) lines.push(`  http-check expect status ${httpCheck.expectStatus}`);
      }
      const tcpCheck = b.tcpCheck as { connect?: boolean; send?: string; expect?: string } | null;
      if (b.mode === 'tcp' && tcpCheck) {
        if (tcpCheck.connect) lines.push('  tcp-check connect');
        if (tcpCheck.send) lines.push(`  tcp-check send ${tcpCheck.send}`);
        if (tcpCheck.expect) lines.push(`  tcp-check expect ${tcpCheck.expect}`);
      }

      for (const a of b.acls) lines.push(`  acl ${a.name} ${a.expression}`);
      for (const r of b.httpRules.sort((x, y) => x.ordinal - y.ordinal)) {
        lines.push(`  ${this.renderHttpRule(r)}`);
      }
      for (const r of b.tcpRules.sort((x, y) => x.ordinal - y.ordinal)) {
        lines.push(`  ${this.renderTcpRule(r)}`);
      }

      for (const s of b.servers.sort((x, y) => x.name.localeCompare(y.name))) {
        lines.push(`  ${this.renderServer(s)}`);
      }
      if (b.rawExtra) lines.push(indent(b.rawExtra, 2));
      lines.push('');
      out.push(lines.join('\n'));
    }
    return out.join('\n');
  }

  private renderListens(listens: ClusterWithIncludes['listens']): string {
    const out = [this.header()];
    for (const l of listens) {
      const lines: string[] = [`listen ${l.name}`, `  mode ${l.mode}`, `  balance ${l.balance}`];
      for (const b of l.binds) lines.push(`  ${this.renderBind(b)}`);
      for (const s of l.servers.sort((x, y) => x.name.localeCompare(y.name))) {
        lines.push(`  ${this.renderServer(s)}`);
      }
      if (l.rawExtra) lines.push(indent(l.rawExtra, 2));
      lines.push('');
      out.push(lines.join('\n'));
    }
    return out.join('\n');
  }

  private renderPeers(peers: ClusterWithIncludes['peers']): string {
    const out = [this.header()];
    for (const p of peers) {
      const lines: string[] = [`peers ${p.name}`];
      const arr = (p.peers as Array<{ name: string; address: string; port: number }>) ?? [];
      for (const peer of arr) {
        lines.push(`  peer ${peer.name} ${peer.address}:${peer.port}`);
      }
      if (p.rawExtra) lines.push(indent(p.rawExtra, 2));
      lines.push('');
      out.push(lines.join('\n'));
    }
    return out.join('\n');
  }

  private renderResolvers(resolvers: ClusterWithIncludes['resolvers']): string {
    const out = [this.header()];
    for (const r of resolvers) {
      const lines: string[] = [`resolvers ${r.name}`];
      const ns = (r.nameservers as Array<{ name: string; address: string; port: number }>) ?? [];
      for (const n of ns) lines.push(`  nameserver ${n.name} ${n.address}:${n.port}`);
      const opts = (r.options as Record<string, string | number> | null) ?? {};
      for (const [k, v] of Object.entries(opts)) lines.push(`  ${k} ${v}`);
      if (r.rawExtra) lines.push(indent(r.rawExtra, 2));
      lines.push('');
      out.push(lines.join('\n'));
    }
    return out.join('\n');
  }

  private renderUserlists(userlists: ClusterWithIncludes['userlists']): string {
    const out = [this.header()];
    for (const u of userlists) {
      const lines: string[] = [`userlist ${u.name}`];
      const groups = (u.groups as Array<{ name: string; users?: string[] }>) ?? [];
      for (const g of groups) {
        lines.push(`  group ${g.name}${g.users ? ' users ' + g.users.join(',') : ''}`);
      }
      const users = (u.users as Array<{ name: string; password?: string; insecurePassword?: string; groups?: string[] }>) ?? [];
      for (const usr of users) {
        const parts = [`  user ${usr.name}`];
        if (usr.password) parts.push(`password ${usr.password}`);
        else if (usr.insecurePassword) parts.push(`insecure-password ${usr.insecurePassword}`);
        if (usr.groups?.length) parts.push(`groups ${usr.groups.join(',')}`);
        lines.push(parts.join(' '));
      }
      if (u.rawExtra) lines.push(indent(u.rawExtra, 2));
      lines.push('');
      out.push(lines.join('\n'));
    }
    return out.join('\n');
  }

  private renderHttpErrors(sections: ClusterWithIncludes['httpErrors']): string {
    const out = [this.header()];
    for (const s of sections) {
      const lines: string[] = [`http-errors ${s.name}`];
      const m = (s.mappings as Record<string, string>) ?? {};
      for (const [code, path] of Object.entries(m)) {
        lines.push(`  errorfile ${code} ${path}`);
      }
      if (s.rawExtra) lines.push(indent(s.rawExtra, 2));
      lines.push('');
      out.push(lines.join('\n'));
    }
    return out.join('\n');
  }

  private renderRings(rings: ClusterWithIncludes['rings']): string {
    const out = [this.header()];
    for (const r of rings) {
      const lines: string[] = [`ring ${r.name}`];
      if (r.description) lines.push(`  description "${r.description}"`);
      if (r.format) lines.push(`  format ${r.format}`);
      lines.push(`  size ${r.size}`);
      const servers = (r.servers as Array<{ name: string; address: string; port: number; options?: string }>) ?? [];
      for (const s of servers) {
        const parts = [`  server ${s.name} ${s.address}:${s.port}`];
        if (s.options) parts.push(s.options);
        lines.push(parts.join(' '));
      }
      if (r.rawExtra) lines.push(indent(r.rawExtra, 2));
      lines.push('');
      out.push(lines.join('\n'));
    }
    return out.join('\n');
  }

  private renderCaches(caches: ClusterWithIncludes['caches']): string {
    const out = [this.header()];
    for (const c of caches) {
      const lines: string[] = [`cache ${c.name}`];
      lines.push(`  total-max-size ${c.totalMaxSize}`);
      lines.push(`  max-object-size ${c.maxObjectSize}`);
      lines.push(`  max-age ${c.maxAge}`);
      if (c.rawExtra) lines.push(indent(c.rawExtra, 2));
      lines.push('');
      out.push(lines.join('\n'));
    }
    return out.join('\n');
  }

  // ────────────────────────────────────────────────────────────────────────

  private renderBind(b: BindWithCert): string {
    const parts: string[] = [`bind ${b.address}:${b.port}`];
    if (b.ssl) parts.push('ssl');
    if (b.crtListRef) parts.push(`crt-list ${b.crtListRef}`);
    else if (b.cert) parts.push(`crt /etc/haproxy/certs/${b.cert.commonName}.pem`);
    if (b.alpn) parts.push(`alpn ${b.alpn}`);
    if (b.proto) parts.push(`proto ${b.proto}`);
    if (b.rawExtra) parts.push(b.rawExtra);
    return parts.join(' ');
  }

  private renderServer(s: ServerLike): string {
    const parts = [`server ${s.name} ${s.address}:${s.port}`];
    if (s.weight !== undefined) parts.push(`weight ${s.weight}`);
    if (s.maxconn) parts.push(`maxconn ${s.maxconn}`);
    if (s.maxqueue) parts.push(`maxqueue ${s.maxqueue}`);
    if (s.check) {
      parts.push('check');
      if (s.checkInter) parts.push(`inter ${s.checkInter}`);
      if (s.fall) parts.push(`fall ${s.fall}`);
      if (s.rise) parts.push(`rise ${s.rise}`);
    }
    if (s.backup) parts.push('backup');
    if (s.disabled) parts.push('disabled');
    if (s.ssl) parts.push('ssl');
    if (s.verify) parts.push(`verify ${s.verify}`);
    if (s.sni) parts.push(`sni ${s.sni}`);
    if (s.rawExtra) parts.push(s.rawExtra);
    return parts.join(' ');
  }

  private renderHttpRule(r: HttpRuleLike): string {
    const phase = r.phase; // request | response | after-response
    const parts = [`http-${phase} ${r.action}`];
    const args = (r.args as Record<string, string | number | boolean> | null) ?? {};
    for (const [k, v] of Object.entries(args)) {
      if (typeof v === 'boolean') {
        if (v) parts.push(k);
      } else {
        parts.push(`${k} ${quoteIfNeeded(String(v))}`);
      }
    }
    const conditions = (r.conditions as Array<{ acl: string; invert?: boolean }> | null) ?? [];
    if (conditions.length) {
      const ifClause = conditions
        .map((c) => (c.invert ? `!${c.acl}` : c.acl))
        .join(' ');
      parts.push(`if ${ifClause}`);
    }
    return parts.join(' ');
  }

  private renderTcpRule(r: TcpRuleLike): string {
    const phase = r.phase; // connection | content | session | response
    const parts = [`tcp-request ${phase} ${r.action}`];
    const args = (r.args as Record<string, string | number | boolean> | null) ?? {};
    for (const [k, v] of Object.entries(args)) {
      if (typeof v === 'boolean') {
        if (v) parts.push(k);
      } else {
        parts.push(`${k} ${quoteIfNeeded(String(v))}`);
      }
    }
    const conditions = (r.conditions as Array<{ acl: string; invert?: boolean }> | null) ?? [];
    if (conditions.length) {
      parts.push(`if ${conditions.map((c) => (c.invert ? `!${c.acl}` : c.acl)).join(' ')}`);
    }
    return parts.join(' ');
  }

  private renderMapEntries(entries: Array<{ key: string; value: string }>): string {
    return entries.map((e) => `${e.key} ${e.value}`).join('\n') + '\n';
  }

  private renderAclList(entries: string[]): string {
    return entries.join('\n') + '\n';
  }

  private renderSpoeAgent(spoe: ClusterWithIncludes['spoeAgents'][number]): string {
    const lines: string[] = ['# Generated by HAFlux'];
    const cfg = (spoe.config as Record<string, unknown>) ?? {};
    // Минимальный формат: пользователь редактирует JSON, а мы рендерим YAML-like структуру SPOE.
    // Полная реализация — task v1.0 (см. SPEC §5.10).
    lines.push(`[${spoe.name}]`);
    for (const [k, v] of Object.entries(cfg)) {
      lines.push(`${k} = ${typeof v === 'object' ? JSON.stringify(v) : String(v)}`);
    }
    if (spoe.rawExtra) lines.push(spoe.rawExtra);
    return lines.join('\n') + '\n';
  }
}

// ─── helpers / типы для include-payload ─────────────────────────────────

function indent(s: string, n: number): string {
  const pad = ' '.repeat(n);
  return s
    .split('\n')
    .map((l) => (l.length ? pad + l : l))
    .join('\n');
}

function quoteIfNeeded(s: string): string {
  if (/^[A-Za-z0-9_./:%@,-]+$/.test(s)) return s;
  return `"${s.replace(/"/g, '\\"')}"`;
}

type ClusterWithIncludes = Prisma.ClusterGetPayload<{
  include: {
    global: true;
    defaults: true;
    frontends: { include: { binds: { include: { cert: true } }; acls: true; httpRules: true; tcpRules: true } };
    backends: { include: { servers: true; acls: true; httpRules: true; tcpRules: true } };
    listens: { include: { binds: { include: { cert: true } }; servers: true } };
    peers: true;
    resolvers: true;
    userlists: true;
    httpErrors: true;
    rings: true;
    caches: true;
    maps: true;
    aclLists: true;
    errorFiles: true;
    luaScripts: true;
    spoeAgents: true;
  };
}>;

type BindWithCert = Prisma.BindGetPayload<{ include: { cert: true } }>;
type ServerLike = Prisma.ServerEntryGetPayload<Record<string, never>>;
type HttpRuleLike = Prisma.HttpRuleGetPayload<Record<string, never>>;
type TcpRuleLike = Prisma.TcpRuleGetPayload<Record<string, never>>;
